### ISSUE TITLE
Pen allways draw after activate

### ISSUE THREAD

**Issue by StephanToGo** [z3y/vertex-color-pens#1]
Pen allways draw after activate.
cant reset it or delete the painted lines.

SDK3 Unity 2019.4.29f1

**Comment by z3y** [comment]
something happened in 2019 that made them loose references, your console is full of errors probably.
But I fixed that recently so make sure to download again

**Comment by z3y** [comment]
sorry i just checked again and it lost reference to one game object after importing in a new projec, i really dont know why 2019 keeps doing this but hopefuly this time its fixed

**Comment by z3y** [comment]
Try using the unity package instead, looks like it doesnt work if i just import the exact same thing directly
https://github.com/z3y/vertex-color-pens/releases/

**Comment by z3y** [comment]
![image](https://user-images.githubusercontent.com/33181641/129054747-3ba71608-2008-47d0-8543-19b2ec5f7507.png)
I give up for now, it just doesnt want to stay in 2019. You can by opening the demo scene and closing it or add it manually to each pen.

**Comment by z3y** [comment]
finally fixed 2019 is a nightmare
