### ISSUE TITLE
UdonSharp v1

### ISSUE THREAD

**Issue by ShayBox** [z3y/vertex-color-pens#3]
UdonSharp v1 has not yet been released as stable but this is a notice to update `vertex-color-pens` such that it is compatible with the next version of UdonSharp (by VRChat) not UdonSharp 0.23 (by Community)

**Comment by z3y** [comment]
I noticed that they are broken in editor only. It still works in vrchat just fine. I need to rewrite them because this code is very old and I can probably do it better when I have time

**Comment by z3y** [comment]
Fixed with the new release
